name: benchmark
description: Bare-minimum, highly customizable benchmarking utility for Dart.
version: 0.1.0
  
environment:
  sdk: ">=3.7.0<4.0.0"

dependencies:
  meta:
  logging:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
